
- type: picture-elements
  image: /local/scarbrook.png
  id: "zonk"
  elements:
    - type: state-icon
      entity: binary_sensor.master_bathroom_motion
      tap_action: more-info
      style:
        top: 82%
        left: 35%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.bathroom_motion_2
      tap_action: more-info
      style:
        top: 82%
        left: 52%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.corridor_motion_2
      tap_action: more-info
      style:
        top: 72%
        left: 67%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.living_room_motion_2
      tap_action: more-info
      style:
        top: 44%
        left: 82%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.bedroom_motion_2
      tap_action: more-info
      style:
        top: 36%
        left: 49%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.master_bedroom_motion
      tap_action: more-info
      style:
        top: 63%
        left: 17%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.main_door
      tap_action: more-info
      style:
        top: 89%
        left: 67%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.bedroom_balcony
      tap_action: more-info
      style:
        top: 19%
        left: 46%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)
    - type: state-icon
      entity: binary_sensor.living_room_balcony
      tap_action: more-info
      style:
        top: 19%
        left: 70%
        filter: drop-shadow(2px 2px 3px black)
        transform: translate(-50%, -50%)scale(1.4)

- type: entities
  title: Motion sensors
  show_header_toggle: false
  entities:
    - entity: binary_sensor.living_room_motion_2
      secondary_info: last-changed
    - entity: binary_sensor.corridor_motion_2
      secondary_info: last-changed
    - entity: binary_sensor.bedroom_motion_2
      secondary_info: last-changed
    - entity: binary_sensor.master_bedroom_motion
      secondary_info: last-changed
    - entity: binary_sensor.bathroom_motion_2
      secondary_info: last-changed
    - entity: binary_sensor.master_bathroom_motion
      secondary_info: last-changed
    - entity: group.motion_sensors
      secondary_info: last-changed

- type: entities
  title: Door sensors
  show_header_toggle: false
  entities:
    - entity: binary_sensor.main_door
      secondary_info: last-changed
    - entity: binary_sensor.living_room_balcony
      secondary_info: last-changed
    - entity: binary_sensor.bedroom_balcony
      secondary_info: last-changed
- type: picture-entity
  title: Bedroom
  entity: camera.patologia
  camera_image: camera.patologia
  show_info: true
  show_state: false
  tap_action:
    action: more-info

- type: alarm-panel
  entity: alarm_control_panel.home_alarm



- type: custom:mini-graph-card
  name: Motion last hour
  entities:
    - entity: binary_sensor.living_room_motion_2
      name: Living room
    - entity: binary_sensor.corridor_motion_2
      name: Corridor
    - entity: binary_sensor.master_bedroom_motion
      name: Master bed.
      color: green
    - entity: binary_sensor.bedroom_motion_2
      name: Bedroom
  hours_to_show: 1
  points_per_hour: 60
  update_interval: 30
  aggregate_func: max
  line_width: 2
  smoothing: false
  state_map:
    - value: "off"
      label: Clear
    - value: "on"
      label: Detected
  hour24: true
  
- type: custom:mini-graph-card
  name: Motion at home
  entities:
    - entity: group.motion_sensors
      name: Home
  hours_to_show: 1
  points_per_hour: 60
  update_interval: 30
  aggregate_func: max
  line_width: 2
  smoothing: false
  state_map:
    - value: "off"
      label: Clear
    - value: "on"
      label: Detected
  hour24: true