- platform: alpha_vantage
  api_key: !secret alpha_vantage_key
  symbols:
    - name: Microsoft
      currency: USD
      symbol: MSFT
    - name: CD Projekt
      currency: PLN
      symbol: CDR.WA
      
- platform: github
  access_token: !secret github_access_token
  repositories:
      - path: 'maxwroc/battery-state-card'
      - path: 'maxwroc/hideseek-mod'
      - path: 'maxwroc/urleditorpro'
      - path: 'maxwroc/github-flexi-card'