
- platform: rfxtrx
  automatic_add: true
  devices:
    115a02108982000000043600007d87521279:
      name: OWL
      data_type:
        - Energy usage
        - Total usage
    08500a2d2b01003669:
      name: Temp outside
      data_type:
        - Temperature
        - Battery numeric