- platform: snmp
  host: 192.168.2.103
  baseoid: 1.3.6.1.4.1.2021.2.1.100.1
  name: Bananapi samba
  value_template: >-
    {% if value | int == 0 %}
      Running
    {% else %}
      Stopped
    {% endif %}

- platform: snmp
  host: 192.168.2.103
  baseoid: 1.3.6.1.2.1.25.1.1.0
  name: Bananapi uptime
  value_template: >-
    {% if (value | int / 8640000) > 0 %}
      {{ (value | int / 8640000) | int }} days
    {% elif (value | int / 360000) > 0 %}
      {{ (value | int / 360000) | int }} hours
    {% elif (value | int / 6000) > 0 %}
      {{ (value | int / 6000) | int }} minutes
    {% else %}
      {{ (value | int / 100) | int }} seconds
    {% endif  %}