
- platform: template
  sensors:

    pc_status:
      icon_template: mdi:desktop-tower-monitor
      friendly_name: "PC"
      value_template: "{% if is_state('device_tracker.pc', 'home') %}On{% else %}Off{% endif %}"

    energy_usage:
      friendly_name: "Power"
      unit_of_measurement: W
      value_template: "{{ states('sensor.owl_energy_usage') | int }}"
    energy_total:
      friendly_name: "Energy total"
      unit_of_measurement: kWh
      value_template: >
        {% if states('sensor.owl_total_usage') | float == 0 %}
         {{ states('sensor.energy_total') }}
        {% else %}
         {{ states('sensor.owl_total_usage') | float | multiply(0.001) | round(1) }}
        {% endif %}
    energy_total_rpi:
      friendly_name: "RPi total energy"
      unit_of_measurement: Wh
      value_template: "{{ state_attr('switch.raspberrypi4', 'total_energy_kwh') | float | multiply(1000) | round(0) }}"

#    livingroom_thsensor_battery:
#      icon_template: >-
#          {% if state_attr('sensor.living_room_temp', 'battery') | int < 20 %}
#            mdi:battery-alert-variant-outline
#          {% else %}
#            mdi:battery
#          {% endif %}
#      friendly_name: "Living room T/H sensor"
#      value_template: "{{ state_attr('sensor.living_room_temp', 'battery') }}"
#      unit_of_measurement: "%"