- id: '1619970101077'
  alias: Test UI automation
  description: ''
  trigger:
  - platform: webhook
    webhook_id: zonk
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: hello
      title: sadfdsaf
  mode: single
- id: '1619970261165'
  alias: Test UI auto
  description: sdafasdfafdsasd
  trigger:
  - platform: webhook
    webhook_id: zonk
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: hello
      message: zsdadsa asdasd a
  mode: single
- id: '1619970449241'
  alias: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz sdfdsafdsa
  description: sdaf s dfs sd adsdfda
  trigger:
  - platform: webhook
    webhook_id: zonki
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: zonk
      message: zasdasdas
  mode: single
- id: '1619994059726'
  alias: kkkkkkkkkkkkkkkkkkkkkkkkk
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: hello
      message: kuku
  mode: single
- id: '1641159435594'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.pushover
        data:
          message: Device battery low
          title: Battery checker
      day: 6
      exclude:
        entity_id:
        - sensor.huawei_p20_pro_battery_level
        - sensor.oneplus_3_battery_level
