homeassistant:
  # Name of the location where Home Assistant is running
  name: Scarbrook
  customize: !include customize.yaml
  whitelist_external_dirs:
    # required to check db size via sensor
    - /config


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

light: !include configuration_lights.yaml
sensor: !include configuration_sensors.yaml
binary_sensor: !include configuration_bsensors.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state
  
hacs:
  token: !secret hacs_token
  appdaemon: true
  theme: true

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

google:
  client_id: !secret google_calendar_api_clientid
  client_secret: !secret gogole_calendar_api_secret
  
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false


device_tracker:
  - platform: ping
    hosts:
      maks: 192.168.2.126
      magduska: 192.168.2.247
      pc: 192.168.2.102

camera:
  - platform: mjpeg
    name: "Bedroom"
    mjpeg_url: http://192.168.2.125/mjpeg.cgi

weblink:
    entities:
      - name: "Router"
        url: http://192.168.2.1
        icon: mdi:router-wireless
      - name: "Sonoff Touch: Bathroom"
        url: http://192.168.2.115
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Master bathroom"
        url: http://192.168.2.119
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Bedroom"
        url: http://192.168.2.120
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Master bedroom"
        url: http://192.168.2.121
        icon: mdi:doorbell-video
      - name: "Node Red"
        url: http://192.168.2.103:1880
        icon: mdi:hammer
      - name: "Black night light"
        url: http://192.168.2.110
        icon: mdi:power-socket-uk
      - name: "Desk light"
        url: http://192.168.2.107
        icon: mdi:power-socket-uk
      - name: "Night light"
        url: http://192.168.2.108
        icon: mdi:power-socket-uk
      - name: "Living room lamp"
        url: http://192.168.2.118
        icon: mdi:power-socket-uk
      - name: "Tv light"
        url: http://192.168.2.109
        icon: mdi:power-socket-uk

history_graph:
  gr1:
    name: "Home temperature"
    hours_to_show: 48
    entities:
      - sensor.living_room_temp
      - sensor.bedroom_temp
      - sensor.master_bed_temp
      
utility_meter:
  energy_daily:
    source: sensor.energy
    cycle: daily
  energy_monthly:
    source: sensor.energy
    cycle: monthly
  energy_yearly:
    source: sensor.energy
    cycle: yearly
      
shell_command:
  commit_config_files: cd /config && git add -A && git commit -m "`date`" && git push -u origin master