homeassistant:
  unit_system: metric
  time_zone: Europe/London
  # Name of the location where Home Assistant is running
  name: Scarbrook
  customize: !include configuration/customize.yaml
  whitelist_external_dirs:
    # required to check db size via sensor
    - /config


# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

########## Start of integrations from default_config ##########
#cloud:
config:
#frontend: # enabled later
#history: # enabled later
logbook:
#map:
#mobile_app:
#person
#script: # enabled later
ssdp:
sun:
system_health:
updater:
zeroconf:
stream:
########### End of integrations from default config ###########

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

wake_on_lan:

recorder:
  purge_keep_days: 14
  purge_interval: 1
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater

history:
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater

group: !include configuration/groups.yaml
automation: !include_dir_merge_list configuration/automations
script: !include_dir_merge_named configuration/scripts

light: !include configuration/lights.yaml
sensor: !include_dir_merge_list configuration/sensors
binary_sensor: !include configuration/binary_sensors.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_token
  appdaemon: true
  theme: true

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_calendar_api_clientid
  client_secret: !secret gogole_calendar_api_secret

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false


device_tracker:
  - platform: ping
    hosts:
      maks: 192.168.2.126
      magduska: 192.168.2.247
      pc: 192.168.2.102

camera:
  - platform: generic
    still_image_url: https://cdn-media.itead.cc/media/catalog/product/1/_/1_7_2.jpg
    stream_source: !secret kidscam_stream_hd
    name: "Kids room HD"
  - platform: generic
    still_image_url: https://cdn-media.itead.cc/media/catalog/product/1/_/1_7_2.jpg
    stream_source: !secret kidscam_stream_sd
    name: "Kids room SD"
  - platform: mjpeg
    name: "Patologia"
    mjpeg_url: http://192.168.2.125/mjpeg.cgi
  - platform: ffmpeg
    name: "Kids SD"
    input: !secret kidscam_rtsp

weblink:
    entities:
      - name: "Router"
        url: http://192.168.2.1
        icon: mdi:router-wireless
      - name: "Sonoff Touch: Bathroom"
        url: http://192.168.2.115
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Master bathroom"
        url: http://192.168.2.119
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Bedroom"
        url: http://192.168.2.120
        icon: mdi:doorbell-video
      - name: "Sonoff Touch: Master bedroom"
        url: http://192.168.2.121
        icon: mdi:doorbell-video
      - name: "Node Red"
        url: http://192.168.2.103:1880
        icon: mdi:hammer
      - name: "Black night light"
        url: http://192.168.2.110
        icon: mdi:power-socket-uk
      - name: "Desk light"
        url: http://192.168.2.107
        icon: mdi:power-socket-uk
      - name: "Night light"
        url: http://192.168.2.108
        icon: mdi:power-socket-uk
      - name: "Living room lamp"
        url: http://192.168.2.118
        icon: mdi:power-socket-uk
      - name: "Tv light"
        url: http://192.168.2.109
        icon: mdi:power-socket-uk

tplink:
  discovery: false
  switch:
    - host: 192.168.4.235

rfxtrx:
  device: /dev/ttyUSB0

emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities:
    light.living_room_lights:
      name: "Living room lights"
      hidden: false
    light.kitchen_lights:
      name: "Kitchen lights"
      hidden: false
    light.kitchen_worktop_lights:
      name: "Kitchen worktop lights"
      hidden: false
    light.living_room_lamp:
      name: "Living room lamp"
      hidden: false
    light.tv_light:
      name: "TV light"
      hidden: false
    light.bedroom_lights:
      name: "Bedroom lights"
      hidden: false
    light.black_night_light:
      name: "Black night light"
      hidden: false
    switch.master_bed_wall_switch_main:
      name: "Master bedroom lights"
      hidden: false
    light.master_bedroom_night_light:
      name: "Night light"
      hidden: false
    light.desk_light:
      name: "Desk light"
      hidden: false
    light.master_bathroom_lights:
      name: "Master bathroom lights"
      hidden: false
    light.bathroom_lights:
      name: "Bathroom lights"
      hidden: false
    switch.pc:
      name: "PC"
      hidden: false

switch:
  - platform: rfxtrx
    automatic_add: false
    devices:
      0b11002f00efde0201040f70:
        name: Doorbell
        fire_event: true
      0b11001b012de8520b000070:
        name: "Nexa mb left"
        fire_event: true
      0b110037012de8520c010f60:
        name: "Nexa mb right"
        fire_event: true

  - platform: wake_on_lan
    name: "PC"
    mac: "90:B1:1C:92:C6:93"
    host: "192.168.2.102"
    broadcast_address: "192.168.2.255"


history_graph:
  gr1:
    name: "Home temperature"
    hours_to_show: 48
    entities:
      - sensor.living_room_temp
      - sensor.bedroom_temp
      - sensor.master_bed_temp

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_appkey
    user_key: !secret pushover_userkey


utility_meter:
  energy_daily:
    source: sensor.energy_total
    cycle: daily
  energy_monthly:
    source: sensor.energy_total
    cycle: monthly
  energy_yearly:
    source: sensor.energy_total
    cycle: yearly
  energy_rpi_monthly:
    source: sensor.energy_total_rpi
    cycle: monthly

shell_command:
  commit_config_files: cd /config && git add -A && git commit -m "`date`" && git push -u origin master
  store_creds: !secret github_store_creds_cmd