homeassistant:
  customize: !include configuration/customize.yaml
  unit_system: metric
  time_zone: Europe/London
  # Name of the location where Home Assistant is running
  name: Scarbrook
  whitelist_external_dirs:
    # required to check db size via sensor
    - "/config"
  latitude: !secret location_lat
  longitude: !secret location_long
  packages: !include_dir_named configuration/packages
  currency: GBP

# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

#panel_custom:
#  - name: sublime-floorplan-card
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:floor-plan
#    url_path: floorplan
#    js_url: "http://127.0.0.1:8080/dist/sublime-floorplan-card.js"
#    config:
#      entity: zonk

########## Start of integrations from default_config ##########
# Default config integrations: https://www.home-assistant.io/integrations/default_config/
# Select all, copy to Notepad++, ctrl+h, Replace string: ^.*\((.*?)\), Replace with: $1:
automation: !include_dir_merge_list configuration/automations
#cloud:
config:
counter:
dhcp:
energy:
frontend:
  themes: !include_dir_merge_named themes/
history:
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater
#image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
#map:
#media_source:
mobile_app:
my:
person:
#scene:
script: !include_dir_merge_named configuration/scripts
ssdp:
stream:
sun:
system_health:
#tag:
timer:
updater:
usb:
webhook:
zeroconf:
#zone:
########### End of integrations from default config ###########

group: !include configuration/groups.yaml
light: !include configuration/lights.yaml
sensor: !include_dir_merge_list configuration/sensors
binary_sensor: !include configuration/binary_sensors.yaml

logger:
  default: warning
  logs:
    homeassistant.components.rfxtrx: info
    homeassistant.components.switch.rfxtrx: info
    homeassistant.components.binary_sensor.rfxtrx: info
    homeassistant.components.rfxtrx.switch: info
    # RFXtrx: debug

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

wake_on_lan:

recorder:
  purge_keep_days: 14
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state
  include: !include configuration/history_include_items.yaml
  exclude:
    entities:
      - binary_sensor.updater

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/transmission-card/transmission-card.js
      type: module
    # Dev
    #  - url: /local/dev/my-custom-card.js?z=v1
    #    type: module
    #  - url: /local/dev/github-flexi-card.js?z=v1
    #    type: module
    #  - url: /local/dev/mini-graph-card/dist/mini-graph-card-bundle.js?v=0.8.8
    #    type: module
    #  - url: /local/dev/battery-state-card/dist/battery-state-card.js?z=v1
    #    type: module
    #  - url: /local/dev/github-flexi-card.js?z=v1
    #    type: module
    #  - url: http://127.0.0.1:5500/dist/battery-state-card.js
    #    type: module
    #  - url: /local/dev/sublime-floorplan-card/dist/sublime-floorplan-card.js
    #    type: module
    - url: /local/dev/alarm-panel-card/dist/alarm-panel-card.js
      type: module

hacs:
  token: !secret hacs_token
  appdaemon: true

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_calendar_api_clientid
  client_secret: !secret gogole_calendar_api_secret

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false

device_tracker:
  - platform: ping
    hosts:
      maks: 192.168.2.126
      magduska: 192.168.2.247
      pc: 192.168.2.102
      laptop_surface: 192.168.2.120

camera:
  - platform: generic
    still_image_url: https://cdn-media.itead.cc/media/catalog/product/1/_/1_7_2.jpg
    stream_source: !secret kidscam_stream_hd
    name: "Kids room HD"
  - platform: generic
    still_image_url: https://cdn-media.itead.cc/media/catalog/product/1/_/1_7_2.jpg
    stream_source: !secret kidscam_stream_sd
    name: "Kids room SD"
  - platform: mjpeg
    name: "Patologia"
    mjpeg_url: http://192.168.2.125/mjpeg.cgi
  - platform: ffmpeg
    name: "Kids SD"
    input: !secret kidscam_rtsp

tplink:
  discovery: false
  switch:
    - host: 192.168.4.235 #hs110-rasp
    - host: 192.168.4.228 #kp115-1

rfxtrx:
  device: /dev/ttyUSB0
  automatic_add: false
  devices:
    0b1100de00efde0201040f70:
      #name: Doorbell
      fire_event: true
    0b11002f00efde0201040f70:
      #name: Doorbell old
      fire_event: true
    0b11001b012de8520b000070:
      #name: "Nexa lr right"
      fire_event: true
    0b110037012de8520c010f60:
      #name: "Nexa lr left"
      fire_event: true
    0b11001d00a0e54e0b000060:
      #name: "Nexa mb left"
      fire_event: true
    0b11001800a0e54e0c010f70:
      #name: "Nexa mb right"
      fire_event: true
    115a02108982000000043600007d87521279:
      #name: OWL
    #0850060e010100c779:
    0a5208af010100c03f0169:
      #name: Temp outside

  #   # OWL
  #   "89":
  #   #"89:82":

  #   # TH outside
  #   "01":
  #   #"01:01":

  #   # Nexa lr
  #   12de852:
  #     fire_event: true

  #   # Nexa lr left
  #   #"12de852:12":
  #   #  fire_event: true

  #   # Nexa lr right
  #   #"12de852:11":
  #   #  fire_event: true

  #   # Nexa mb
  #   "0a0e54e":
  #     fire_event: true

  # Nexa mb left
  #"0a0e54e:11":
  #  fire_event: true

  # Nexa mb right
  #"0a0e54e:12":
  #  fire_event: true

  # OWL
  #115a02108982000000043600007d87521279:

  # T/H sensor outside
  #0850060e010100c779:
  #0a5208af010100c03f0169:

  # Doorbell
  #0b11002f00efde0201040f70:
  # 0b1100de00efde0201040f70:
  #   fire_event: true

  # Nexa lr right
  #0b11001b012de8520b000070:
  # 0b11004d012de8520b010f60:
  #   fire_event: true
  # 0b110051012de8520b000060:
  #   fire_event: true
  # 0b1100a8012de8520b000060:
  #   fire_event: true

  # Nexa lr left
  # 0b1100ab012de8520c000060:
  # #0b110037012de8520c010f60:
  #   fire_event: true

  # # Nexa mb left
  # #0b11001d00a0e54e0b000060:
  # 0b11003600a0e54e0b010f60:
  #   fire_event: true

  # # Nexa mb right
  # #0b11001800a0e54e0c010f70:
  # 0b11002900a0e54e0c000060:
  #   fire_event: true

emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities:
    light.living_room_lights:
      name: "Living room lights"
      hidden: false
    light.kitchen_lights:
      name: "Kitchen lights"
      hidden: false
    light.kitchen_worktop_lights:
      name: "Kitchen worktop lights"
      hidden: false
    light.living_room_lamp:
      name: "Living room lamp"
      hidden: false
    light.tv_light:
      name: "TV light"
      hidden: false
    light.bedroom_lights:
      name: "Bedroom lights"
      hidden: false
    light.black_night_light:
      name: "Black night light"
      hidden: false
    switch.master_bed_wall_switch_main:
      name: "Master bedroom lights"
      hidden: false
    light.master_bedroom_night_light:
      name: "Night light"
      hidden: false
    light.desk_light:
      name: "Desk light"
      hidden: false
    light.master_bathroom_lights:
      name: "Master bathroom lights"
      hidden: false
    light.bathroom_lights:
      name: "Bathroom lights"
      hidden: false
    switch.pc:
      name: "PC"
      hidden: false

sonoff:
  username: !secret ewelink_user
  password: !secret ewelink_pass
#  mode: local
#  reload: always  # update device list every time HA starts

switch: !include configuration/switches.yaml

notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_appkey
    user_key: !secret pushover_userkey
  - name: Pushover Git
    platform: pushover
    api_key: !secret pushover_git_appkey
    user_key: !secret pushover_userkey

shell_command:
  commit_config_files: cd /config && git pull && git add -A && git commit -m "`date`" && git push -u origin master
  store_creds: !secret github_store_creds_cmd # git config --global user.name "USERNAME" && git config --global user.email "USER@EMAIL" && git config --global credential.helper store && echo "https://USERNAME:GITTOKEN@github.com" > ~/.git-credentials
