- platform: mqtt
  name: "Power"
  icon: mdi:current-ac
  state_topic: "sensor/utility/power"
  value_template: "{{ value_json.value }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: "Energy"
  state_topic: "sensor/utility/energy"
  json_attributes_topic: "sensor/utility/energy"
  icon: mdi:flash
  unit_of_measurement: "Wh"
  value_template: "{{ value_json.energy.value | round(1) }}"

- platform: mqtt
  name: "Living room temp"
  state_topic: "sensor/livingroom/temp"
  value_template: "{{ value_json.temperature.value }}"
  json_attributes_topic: "sensor/livingroom/temp"
  json_attributes_template: "{{ value_json.status | tojson }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Living room humidity"
  icon: mdi:water-percent
  state_topic: "sensor/livingroom/temp"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity.value }}"

- platform: mqtt
  name: "Bedroom temp"
  state_topic: "sensor/bedroom/temp"
  value_template: "{{ value_json.temperature.value }}"
  json_attributes_topic: "sensor/bedroom/temp"
  json_attributes_template: "{{ value_json.status | tojson }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Bedroom humidity"
  icon: mdi:water-percent
  state_topic: "sensor/bedroom/temp"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity.value }}"

- platform: mqtt
  name: "Master bed. temp"
  state_topic: "sensor/mbedroom/temp"
  value_template: "{{ value_json.temperature.value }}"
  json_attributes_topic: "sensor/mbedroom/temp"
  json_attributes_template: "{{ value_json.status | tojson }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Master bed. humidity"
  icon: mdi:water-percent
  state_topic: "sensor/mbedroom/temp"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity.value }}"

- platform: mqtt
  name: "Outside temp"
  state_topic: "sensor/outside/temp"
  value_template: "{{ value_json.temperature.value }}"
  json_attributes_topic: "sensor/outside/temp"
  json_attributes_template: "{{ value_json.status | tojson }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Outside humidity"
  icon: mdi:water-percent
  state_topic: "sensor/outside/temp"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity.value }}"

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db

- platform: uptime
  name: Time online

- platform: command_line
  name: "Config last backup"
  command: cd /config && git --no-pager log -n 1 --pretty=%cd --date=local origin/master
  scan_interval: 60

- platform: command_line
  name: "Files changed locally"
  command: cd /config && git status -suno | wc -l
  scan_interval: 60

- platform: command_line
  name: CPU temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'





- platform: template
  sensors:

    pc_status:
      icon_template: mdi:desktop-tower-monitor
      friendly_name: "PC"
      value_template: "{% if is_state('device_tracker.pc', 'home') %}On{% else %}Off{% endif %}"


#    livingroom_thsensor_battery:
#      icon_template: >-
#          {% if state_attr('sensor.living_room_temp', 'battery') | int < 20 %}
#            mdi:battery-alert-variant-outline
#          {% else %}
#            mdi:battery
#          {% endif %}
#      friendly_name: "Living room T/H sensor"
#      value_template: "{{ state_attr('sensor.living_room_temp', 'battery') }}"
#      unit_of_measurement: "%"