resources:
#  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/atomic_calendar/atomic_calendar.js
    type: module
  - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
    type: module
#  - url: /hacsfiles/battery-state-card/battery-state-card.js
#    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
# Dev
  - url: /local/dev/mini-graph-card/dist/mini-graph-card-bundle.js?v=0.8.8
    type: module
  - url: /local/dev/battery-state-card/dist/battery-state-card.js
    type: module

title: Home
views:
  - title: Home
    icon: mdi:home
    cards: !include lovelace/overview.yaml
  - title: Kids
    cards: !include lovelace/kids.yaml
#  - title: Floor plan
#    panel: true
#    cards: !include lovelace/floorplan.yaml
  - title: Media
    cards: !include lovelace/media.yaml
  - title: Security
    cards: !include lovelace/security.yaml
  - title: Admin
    cards: !include lovelace/admin.yaml
  - title: Test
    cards: !include lovelace/test.yaml