resources:
#  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module
#  - url: /hacsfiles/github-flexi-card/github-flexi-card.js
#    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/github-card/github-card.js
    type: module
# Dev
  - url: /local/dev/mini-graph-card/dist/mini-graph-card-bundle.js?v=0.8.8
    type: module
  - url: /local/dev/github-flexi-card.js?z=v1
    type: module
#  - url: /local/dev/battery-state-card/dist/battery-state-card.js?z=v1
#    type: module
#  - url: /local/dev/sublime-floorplan-card/dist/sublime-floorplan-card.js
#    type: module

title: Home
views:
  - title: Home
    icon: mdi:home
    path: home
    cards: !include lovelace/overview.yaml
  - title: Kids
    path: kids
    cards: !include lovelace/kids.yaml
#  - title: Floor plan
#    panel: true
#    cards: !include lovelace/floorplan.yaml
  - title: Media
    path: media
    cards: !include lovelace/media.yaml
  - title: Security
    path: security
    cards: !include lovelace/security.yaml
  - title: Admin
    path: admin
    cards: !include lovelace/admin.yaml