resources:
#  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
#    type: module
  - url: /local/mini-graph-card/dist/mini-graph-card-bundle.js?v=0.8.8
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /local/atomic_calendar.js
    type: module
  - url: /local/battery-entity.js?v=0.3
    type: module

title: Home
views:
  - title: Home
    icon: mdi:home
    cards: !include lovelace/overview.yaml
  - title: Kids
    cards: !include lovelace/kids.yaml
#  - title: Floor plan
#    panel: true
#    cards: !include lovelace/floorplan.yaml
  - title: Media
    cards: !include lovelace/media.yaml
  - title: Security
    cards: !include lovelace/security.yaml
  - title: Admin
    cards: !include lovelace/admin.yaml
  - title: Test
    cards: !include lovelace/test.yaml