sensor:
  - platform: github
    access_token: !secret github_access_token
    repositories:
        - path: 'maxwroc/battery-state-card'
        - path: 'maxwroc/hideseek-mod'
        - path: 'maxwroc/urleditorpro'
        - path: 'maxwroc/github-flexi-card'
        - path: 'maxwroc/homeassistant'
          name: "Home assistant config"

  - platform: gitcustom
    access_token: !secret github_access_token
    repositories:
        - path: 'maxwroc/battery-state-card'

  - platform: template
    sensors:
      battery_state_card_issues:
        friendly_name: "battery-state-card"
        icon_template: "mdi:github"
        value_template: "{{ state_attr('sensor.battery_state_card', 'open_issues') - state_attr('sensor.battery_state_card', 'open_pull_requests') }}"
        attribute_templates:
          # just for automation (to not duplicate automation entry)
          open_issues: "{{ state_attr('sensor.battery_state_card', 'open_issues') - state_attr('sensor.battery_state_card', 'open_pull_requests') }}"
      github_flexi_card_issues:
        friendly_name: "github_flexi_card"
        icon_template: "mdi:github"
        value_template: "{{ state_attr('sensor.github_flexi_card', 'open_issues') - state_attr('sensor.github_flexi_card', 'open_pull_requests') }}"
        attribute_templates:
          # just for automation (to not duplicate automation entry)
          open_issues: "{{ state_attr('sensor.battery_state_card', 'open_issues') - state_attr('sensor.battery_state_card', 'open_pull_requests') }}"

automation:
  - alias: "Notify when Github star is received"
    trigger:
      - platform: state
        entity_id:
          - sensor.battery_state_card
          - sensor.github_flexi_card
          - sensor.urleditorpro
          - sensor.hideseek_mod
          - sensor.homeassistant
        attribute: stargazers
    condition: []
    mode: restart # start a new run after stopping previous run
    action:
      - service: notify.pushover_git
        data:
          message: "Stars changed for '{{ trigger.to_state.attributes.friendly_name }}': {{ trigger.from_state.attributes.stargazers }} => {{ trigger.to_state.attributes.stargazers }}"
          title: "Github"
          data:
            priority: -1
            # -2 to generate no notification/alert
            # -1 to always send as a quiet notification
            #  1 to display as high-priority and bypass the user's quiet hours
            #  2 to also require confirmation from the user

  - alias: "Notify when Github issue is created"
    trigger:
      - platform: state
        entity_id:
          # - sensor.battery_state_card
          # - sensor.github_flexi_card
          - sensor.urleditorpro
          - sensor.hideseek_mod
          - sensor.homeassistant
        attribute: open_issues
      - platform: state
        entity_id:
          - sensor.battery_state_card_issues
          - sensor.github_flexi_card_issues
    condition: []
    mode: restart # start a new run after stopping previous run
    action:
      - service: notify.pushover_git
        data:
          message: "Issues changed for '{{ trigger.to_state.attributes.friendly_name }}': {{ trigger.from_state.attributes.open_issues }} => {{ trigger.to_state.attributes.open_issues }}"
          title: "Github"
          data:
            priority: -1
            # -2 to generate no notification/alert
            # -1 to always send as a quiet notification
            #  1 to display as high-priority and bypass the user's quiet hours
            #  2 to also require confirmation from the user