# homeassistant:
#   customize:
#     sensor.masterbedtemp:
#       friendly_name: "Master bedroom humidity"

sensor:
  - platform: statistics
    name: Outside temperature max
    entity_id: sensor.outside_temperature_fixed
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Outside temperature min
    entity_id: sensor.outside_temperature_fixed
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  # - platform: statistics
  #   name: Living room temp min
  #   entity_id: sensor.livingroomtemp
  #   state_characteristic: value_min
  #   sampling_size: 1440
  #   max_age:
  #     days: 1

  - platform: template
    sensors:
      # This is to fix thermometer or RF transmission bugs resulting in short spikes
      outside_temperature_fixed:
        friendly_name: "Temperature outside"
        unit_of_measurement: "°C"
        device_class: temperature
        value_template: >
          {% if states('sensor.outside_temperature_fixed') | lower == "unavailable" %}
            {{ (states('sensor.outside_temperature_real') | float) }}
          {%- else -%}
            {% if (states("sensor.outside_temperature_real") | float - states("sensor.outside_temperature_fixed") | float) | abs > 10 %}
            {{ states('sensor.outside_temperature_fixed') }}
            {% else %}
            {{ states('sensor.outside_temperature_real') | float | round(1) }}
            {% endif %}
          {%- endif %}
