homeassistant:
  customize:
    sensor.masterbedtemp:
      friendly_name: "Master bedroom humidity"

sensor:
  - platform: template
    sensors:
      living_room_temp_fixed:
        friendly_name: "Living room temperature"
        device_class: temperature
        unit_of_measurement: °C
        value_template: >
          {% if states('sensor.living_room_temp_fixed') | lower == "unavailable" %}
            {{ (states('sensor.livingroomtemp') | float) }}
          {%- else -%}
            {% if (states('sensor.livingroomtemp') | float - states('sensor.living_room_temp_fixed') | float) | abs > 10 %}
              {{ (states('sensor.living_room_temp_fixed') | float) }}
            {%- else -%}
              {{ (states('sensor.livingroomtemp') | float) }}
            {%- endif %}
          {%- endif %}

  - platform: statistics
    name: "Living room temp. fixed max"
    entity_id: sensor.living_room_temp_fixed
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: "Living room temp. fixed min"
    entity_id: sensor.living_room_temp_fixed
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Outside temp max
    entity_id: sensor.thermometer_outside_temp_fixed
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Outside temp min
    entity_id: sensor.thermometer_outside_temp_fixed
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Kids temp max
    entity_id: sensor.bedroomtemp_2
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Kids temp min
    entity_id: sensor.bedroomtemp_2
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Master bedroom temp max
    entity_id: sensor.masterbedtemp_3
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Master bedroom temp min
    entity_id: sensor.masterbedtemp_3
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Living room temp max
    entity_id: sensor.livingroomtemp
    state_characteristic: value_max
    sampling_size: 1440
    max_age:
      days: 1

  - platform: statistics
    name: Living room temp min
    entity_id: sensor.livingroomtemp
    state_characteristic: value_min
    sampling_size: 1440
    max_age:
      days: 1

  - platform: template
    sensors:
      # This is to fix thermometer or RF transmission bugs resulting in short spikes
      thermometer_outside_temp_fixed:
        friendly_name: "Temperature outside"
        unit_of_measurement: "°C"
        device_class: temperature
        value_template: >
          {% if states('sensor.thermometer_outside_temperature') | float > 40 %}
           {{ states('sensor.thermometer_outside_temp_fixed') }}
          {% else %}
           {{ states('sensor.thermometer_outside_temperature') | float | round(1) }}
          {% endif %}
