- platform: group
  name: Living room all lights
  entities:
    - light.living_room_lamp
    - light.tv_light
    - light.living_room_lights
    - light.kitchen_lights
    - light.kitchen_worktop_lights


#### Living room and kitchen

- platform: mqtt
  name: "Living room lamp"
  command_topic: "lights/livingroom/lamp/cmd/POWER"
  state_topic: "lights/livingroom/lamp/state/POWER"
  json_attributes_topic: "lights/livingroom/lamp/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Tv light"
  command_topic: "lights/livingroom/tvlight/cmd/POWER"
  state_topic: "lights/livingroom/tvlight/state/POWER"
  json_attributes_topic: "lights/livingroom/tvlight/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Living room lights"
  command_topic: "shellies/shelly1-5B2D92/relay/0/command"
  state_topic: "shellies/shelly1-5B2D92/relay/0"
  json_attributes_topic: "lights/livingroom/main/attr"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Kitchen lights"
  command_topic: "shellies/shelly1-32A790/relay/0/command"
  state_topic: "shellies/shelly1-32A790/relay/0"
  json_attributes_topic: "lights/kitchen/main/attr"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Kitchen worktop lights"
  command_topic: "shellies/shelly1-5B3144/relay/0/command"
  state_topic: "shellies/shelly1-5B3144/relay/0"
  json_attributes_topic: "lights/kitchen/worktop/attr"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Christmas tree"
  command_topic: "lights/livingroom/christmastree/cmd/POWER"
  state_topic: "lights/livingroom/christmastree/state/POWER"
  json_attributes_topic: "lights/livingroom/christmastree/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

#### Master bedroom ####

- platform: mqtt
  name: "Desk light"
  command_topic: "lights/mbedroom/desk/cmd/POWER"
  state_topic: "lights/mbedroom/desk/state/POWER"
  json_attributes_topic: "lights/mbedroom/desk/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Master bedroom night light"
  command_topic: "lights/mbedroom/nightlight/cmd/POWER"
  state_topic: "lights/mbedroom/nightlight/state/POWER"
  json_attributes_topic: "lights/mbedroom/nightlight/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

#### Bedroom (kids) ####

- platform: mqtt
  name: "Bedroom lights"
  command_topic: "lights/bedroom/main/cmd/POWER"
  state_topic: "lights/bedroom/main/state/POWER"
  json_attributes_topic: "lights/bedroom/main/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Black night light"
  command_topic: "lights/bedroom/blacknightlight/cmd/POWER"
  state_topic: "lights/bedroom/blacknightlight/state/POWER"
  json_attributes_topic: "lights/bedroom/blacknightlight/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

#### Bathrooms ####

- platform: mqtt
  name: "Bathroom lights"
  command_topic: "lights/bathroom/main/cmd/POWER"
  state_topic: "lights/bathroom/main/state/POWER"
  json_attributes_topic: "lights/bathroom/main/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Master bathroom lights"
  command_topic: "lights/mbathroom/main/cmd/POWER"
  state_topic: "lights/mbathroom/main/state/POWER"
  json_attributes_topic: "lights/mbathroom/main/attr"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true