#########################################################################
# Automatic light switch off
#
#   * Wait at least 20min after motion is not detected. This is to prevent
#     from turning off the lights when someone takes a shower (motion is
#     not detected through glass)
#   * Later we check if the light is still on
#   * Additionally we need to check if motion was not detected meanwhile
#   * After turning of the light we send notification
#########################################################################

- alias: "Bathroom lights auto-turn-off"
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_2
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    - condition: state
      entity_id: light.bathroom_lights
      state: "on"
    - condition: state
      entity_id: binary_sensor.bathroom_motion_2
      state: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bathroom_lights
    - service: notify.pushover
      data:
        message: "Turned off bathroom lights"
        title: "Electricity savings"

- alias: "Bathroom lights auto-turn-off (master)"
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_motion
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    - condition: state
      entity_id: light.master_bathroom_lights
      state: "on"
    - condition: state
      entity_id: binary_sensor.master_bathroom_motion
      state: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bathroom_lights
    - service: notify.pushover
      data:
        message: "Turned off master bathroom lights"
        title: "Electricity savings"

#########################################################################
# Turn off docking station to prevent from monitor to keep waking up (Surface Doc + LG/Samsung monitor)
#########################################################################

- id: electricity_savings_docking_station
  alias: "Docking station auto turn off"
  trigger:
    platform: webhook
    webhook_id: device_lock
  condition:
    - condition: template
      value_template: "{{ trigger.json.device == 'MAKSYMC-LAP' and trigger.json.action == 'locked' }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.docking_station
