
#########################################################################
# Automatic light switch off
#
#   * Wait at least 20min after motion is not detected. This is to prevent
#     from turning off the lights when someone takes a shower (motion is
#     not detected through glass)
#   * Later we check if the light is still on
#   * Additionally we need to check if motion was not detected meanwhile
#   * After turning of the light we send notification
#########################################################################

- alias: "Bathroom lights auto-turn-off"
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_2
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    - condition: state
      entity_id: light.bathroom_lights
      state: "on"
    - condition: state
      entity_id: binary_sensor.bathroom_motion_2
      state: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bathroom_lights
    - service: notify.pushover
      data:
        message: "Turned off bathroom lights"
        title: "Electricity savings"

- alias: "Bathroom lights auto-turn-off (master)"
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_motion
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
    - condition: state
      entity_id: light.master_bathroom_lights
      state: "on"
    - condition: state
      entity_id: binary_sensor.master_bathroom_motion
      state: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bathroom_lights
    - service: notify.pushover
      data:
        message: "Turned off master bathroom lights"
        title: "Electricity savings"


#########################################################################
# Notify when lights are turned on when alarm is armed
#########################################################################

- alias: "Notify when lights are on when alarm is armed"
  trigger:
    platform: state
    entity_id: group.lights
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "armed_away"
  action:
    - service: notify.pushover
      data_template:
        #message: "Light {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}"
        message: "Lights state changed to '{{ trigger.to_state.state }}'"
        title: "Electricity savings"
        data:
          priority: 1