#########################################################################
# Aqara wall switch
#########################################################################

- alias: "Aqara kids wall switch - left button"
  description: "Toggle black night light"
  trigger:
  - device_id: 10dce240078240d1a16ef59c19e9aab8
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.black_night_light
    service: light.toggle

- alias: "Aqara kids wall switch - left button (long press)"
  description: "Night time music for kids"
  trigger:
  - device_id: 10dce240078240d1a16ef59c19e9aab8
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kids_dot
        volume_level: 0.1
    - delay: 1
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "Kids dot"
    - delay: 1
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_type: "playlist"
        media_content_id: "spotify:user:spotify:playlist:37i9dQZF1DX0jgyAiPl8Af" # "spotify:user:spotify:playlist:37i9dQZF1DX3iWJN79KKoY" Chillout covers

- alias: "Aqara kids wall switch - right button"
  description: "Kids room Christmas lights toggle"
  trigger:
  - device_id: 10dce240078240d1a16ef59c19e9aab8
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  condition: []
  action:
    - entity_id: switch.tp_link_kp115_1 # christmass lights
      service: switch.toggle

- alias: "Aqara kids wall switch - right button (long press)"
  description: "Kids favorite song at the time"
  trigger:
  - device_id: 10dce240078240d1a16ef59c19e9aab8
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_long_press
  condition: []
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.kids_dot
        volume_level: 0.4
    - delay: 1
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "Kids dot"
    - delay: 1
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_type: "music"
        media_content_id: "spotify:track:65irrLqfCMRiO3p87P4C0D" # frosty the snowman