#########################################################################
# Aqara wall switch
#########################################################################

- alias: "Aqara livingroom wall switch - left button"
  description: "Toggle livingroom lamp"
  trigger:
  - device_id: 18df814cdc6e42219c9b10cdfd24b51d
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.living_room_lamp
    service: light.toggle
    
- alias: "Aqara livingroom wall switch - right button"
  description: "Toggle TV light"
  trigger:
  - device_id: 18df814cdc6e42219c9b10cdfd24b51d
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.tv_light
    service: light.toggle
  - entity_id: light.christmas_tree
    service: light.toggle
    
- alias: "Aqara livingroom wall switch - left button (long press)"
  description: "Turn off all livingroom/kitchen lights"
  trigger:
  - device_id: 18df814cdc6e42219c9b10cdfd24b51d
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: light.living_room_all_lights
    service: light.turn_off