#########################################################################
# Aqara desk switch
#########################################################################

- alias: "Aqara master bed. desk switch - left button"
  description: "Toggle night light"
  trigger:
  - device_id: 75a7b1408f31448faa7b6f2439a07a64
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.master_bedroom_night_light
    service: light.toggle

- alias: "Aqara master bed. desk switch - left button (long press)"
  description: "Toggle master bathroom lights"
  trigger:
  - device_id: 75a7b1408f31448faa7b6f2439a07a64
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: light.master_bathroom_lights
    service: light.toggle

- alias: "Aqara master bed. desk switch - right button"
  description: "Toggle desk light"
  trigger:
  - device_id: 75a7b1408f31448faa7b6f2439a07a64
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.desk_light
    service: light.toggle

- alias: "Aqara master bed. desk switch - right button (long press)"
  description: "Toggle master bed. main lights"
  trigger:
  - device_id: 75a7b1408f31448faa7b6f2439a07a64
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: switch.master_bed_wall_switch_main
    service: switch.toggle

#########################################################################
# Aqara wall switch
#########################################################################

- alias: "Aqara master bed. wall switch - right button"
  description: "Toggle night light"
  trigger:
  - entity_id: switch.master_bedroom_wall_second
    platform: state
  condition: []
  action:
  - entity_id: light.master_bedroom_night_light
    service: light.toggle