
#########################################################################
# Doorbell pushover notification
#########################################################################
- alias: "Doorbell notification"
  description: "Pushover notification"
  trigger:
    platform: event
    event_type: button_pressed
    event_data:
      entity_id: switch.doorbell
  condition: []
  action:
    - service: notify.pushover
      data:
        message: "Expecting delivery?"
        title: "Doorbell"
        data:
          priority: -1

#########################################################################
# Home Alarm - motion detected
#
# * Sound warrning via Alexa announce on all devices
# * Pushover notification with highest priority
#########################################################################
- alias: "Home alarm - motion detected"
  description: "Triggers alarm when person is detected at home"
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "armed_away"
  action:
    - service: notify.pushover
      data:
        message: "Presence detected"
        title: "Home alarm"
        data:
          priority: 1
    - service: script.audio_notify
      data_template:
        message: "Alarm triggered"