
#########################################################################
# Doorbell pushover notification
#########################################################################
- alias: "Doorbell notification"
  description: "Pushover notification"
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      packet_type: 17
      sub_type: 0
      id_string: "0efde02:1"
  condition: []
  mode: single # do not start a new one in case of multiple events
  action:
    - service: notify.pushover
      data:
        message: "Expecting delivery?"
        title: "Doorbell"
        data:
          priority: 0
          # -2 to generate no notification/alert
          # -1 to always send as a quiet notification
          #  1 to display as high-priority and bypass the user's quiet hours
          #  2 to also require confirmation from the user

#########################################################################
# Home Alarm - motion detected
#
# * Sound warrning via Alexa announce on all devices
# * Pushover notification with highest priority
#########################################################################
- alias: "Home alarm - motion detected"
  description: "Triggers alarm when person is detected at home"
  trigger:
    - platform: state
      entity_id: group.motion_sensors
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: "armed_away"
  action:
    - service: notify.pushover
      data:
        message: "Presence detected"
        title: "Home alarm"
        data:
          priority: 1
          # -2 to generate no notification/alert
          # -1 to always send as a quiet notification
          #  1 to display as high-priority and bypass the user's quiet hours
          #  2 to also require confirmation from the user
    - service: script.audio_notify
      data_template:
        message: "Alarm triggered"