

#########################################################################
# Notify when state changes reporting diff and old/new state
#########################################################################

- alias: "Raspwroc files count changed notification"
  initial_state: true
  trigger:
    platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.files_on_raspwroc
  condition: []
  action:
    - service: notify.pushover
      data_template:
        message: "Number of files changed: {{ trigger.event.data.new_state.state | int - trigger.event.data.old_state.state | int }} ({{ trigger.event.data.old_state.state }}/{{ trigger.event.data.new_state.state }})"
        title: "Raspwroc"

#########################################################################
# Notify when state changes reporting diff and old/new state
#########################################################################

- alias: "Restore Samba Backup sensor on startup"
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: restore-sensor
  mode: single