esphome:
  name: living_room_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room Lamp"
    password: "UhSz6Ltn5jUU"
    
  use_address: 192.168.4.246

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass
   
#############################
# Sonoff S20
############################# 

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Living room lamp button"
    on_press:
      - light.toggle: lightid
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay
    
light:
  - platform: binary
    name: "Living room lamp"
    output: relay
    id: lightid
  
status_led:
  pin:
    number: GPIO13
    inverted: no
