esphome:
  name: test_board
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Board Fallback Hotspot"
    password: "jd8Bh9xhQua9"
  
  use_address: 192.168.4.228

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass
  
binary_sensor:
  - platform: gpio
    pin: 
      number: 34
      inverted: True
    name: "Noise sensor"
    id: noise
    #filters:
    #  - delayed_on: 1s

sensor:
  - platform: dht
    pin: 35
    model: DHT11
    temperature:
      name: "Living Room Temperature"
      id: my_temp
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

font:
  - file: "OpenSans-Regular.ttf"
    id: my_font
    size: 10
    
i2c:
  sda: 4
  scl: 15

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: 16
    address: 0x3C
    lambda: |-
      it.printf(2, 7, id(my_font), "Noise: %s", id(noise).state ? "On" : "Off");
      it.printf(2, 20, id(my_font), "Temp: %.1f", id(my_temp).state);