esphome:
  name: tv_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tv Light Fallback Hotspot"
    password: "qdgn5aeAffYF"
    
  use_address: 192.168.4.247

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass

#############################
# Sonoff S20
#############################

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "TV light button"
    on_press:
      - light.toggle: lightid
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay
    
light:
  - platform: binary
    name: "TV light"
    output: relay
    id: lightid
    
status_led:
  pin:
    number: GPIO13
    inverted: no
